<?php


namespace Asdrubael\Utils;


class treeImage extends treeHandler
{
    const IMAGE_LIMIT = 1000;

    protected $allowedFields = [
        'UID', 'ФайлКартинки'
    ];

    function __construct()
    {
        parent::__construct();
    }

    protected function fillInOutputArr($uri)
    {
        parent::fillInOutputArr($uri); // TODO: Change the autogenerated stub
    }

    protected function send($uri){

        $success = false;
        $client = new \GuzzleHttp\Client();
        $response = $client->request('GET', $uri);

        if ($response->getStatusCode() == 200) {

            $outArr = json_decode($response->getBody(), true);

            foreach($outArr as &$item){
                foreach($item as $key => $value){
                    if( !in_array($key, $this->allowedFields) ){
                        unset($item[$key]);
                    }
                }
            }
            //echo '<pre>' . print_r($outArr, true) . '</pre>';die();
            file_put_contents($this->tempJsonPath, json_encode($outArr));
            $this->outputArr = array_slice(
                $outArr,
                0,
                self::IMAGE_LIMIT
            );

            $success = true;
        } else {
            echo "error: status: " . $response->getStatusCode();
            die();
        }
        //echo '<pre>' . print_r($this->outputArr, true) . '</pre>';die();
        return $success;
    }


    public function getPicture( $gui ){

        $client = new \GuzzleHttp\Client();
        $response = $client->request('GET', $this->points['image'] . $gui);
        //echo '<pre>' . print_r($this->points['image'] . $gui, true) . '</pre>';
        if ($response->getStatusCode() == 200) {
            return json_decode($response->getBody(), true );
        }
        return false;
    }
}