<?php
return [
    "bx" => [
        'TIME_LIMIT' => 50,
        'PARENT_ID' => 'Родитель',
        'ID' => "UID",
        'NAME' => "Наименование",
        'CHILDREN' => 'CHILDREN',
        'DEPTH_LEVEL' => 'DEPTH_LEVEL',
        'FULL_NAME' => "НаименованиеПолное",
        'PROPERTIES' => "Свойства",
        'DESCRIPTION' => 'Описание',
        'PIC_FILE' => 'ФайлКартинки',
    ],
    "tree" => [
        'PRODUCT_LIMIT' => 500,
        'WAITING_TIME' => 0,
        'PARENT_ID' => 'Родитель',
        'ID' => "UID",
        'NAME' => "Наименование",
        'ADDRESS' => 'Адрес',
        'CHILDREN' => 'CHILDREN',
        'DEPTH_LEVEL' => 'DEPTH_LEVEL',
        'FULL_NAME' => "НаименованиеПолное",
        'PROPERTIES' => "Свойства",
        'DESCRIPTION' => 'Описание',
        'PIC_FILE' => 'ФайлКартинки',
        'PROP_POINT_OF_ENTRY' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetScheme/22e8d9ce-ed52-47ca-a524-e32b586aab0a',
        'PROD_POINT_OF_ENTRY' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetCatalog',
        'SECT_POINT_OF_ENTRY' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetSections',
        'GET_IMAGE_URI' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetImage/',
        'REFERENCE_URL' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetReference/',
        'TYPE_PRICE' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetReference/42d10808-9ccb-11e8-a215-00505601048d',
        'PRICE_ENTRY' => '',
        'STORE_ENTRY' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetReference/42d1082d-9ccb-11e8-a215-00505601048d',
    ],
];