<?php
return [
    "bx" => [
        'TIME_LIMIT' => 50,
        'PARENT_ID' => 'Родитель',
        'ID' => "UID",
        'NAME' => "Наименование",
        'CHILDREN' => 'CHILDREN',
        'DEPTH_LEVEL' => 'DEPTH_LEVEL',
        'FULL_NAME' => "НаименованиеПолное",
        'PROPERTIES' => "Свойства",
        'DESCRIPTION' => 'Описание',
        'PIC_FILE' => 'ФайлКартинки',
    ],
    "tree" => [
        'PRODUCT_LIMIT' => 1000,
        'WAITING_TIME' => 0,
        'PARENT_ID' => 'Родитель',
        'ID' => "UID",
        'NAME' => "Наименование",
        'CHILDREN' => 'CHILDREN',
        'DEPTH_LEVEL' => 'DEPTH_LEVEL',
        'FULL_NAME' => "НаименованиеПолное",
        'PROPERTIES' => "Свойства",
        'DESCRIPTION' => 'Описание',
        'PIC_FILE' => 'ФайлКартинки',
       // 'PROP_POINT_OF_ENTRY' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetScheme/22e8d9ce-ed52-47ca-a524-e32b586aab0a',
        'PROP_POINT_OF_ENTRY' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetScheme/22e8d9ce-ed52-47ca-a524-e32b586aab0a',
        //'PROD_POINT_OF_ENTRY' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetFolder/GoodsItems',
        'PROD_POINT_OF_ENTRY' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetCatalog',
        'SECT_POINT_OF_ENTRY' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetFolder/GoodsOnlyGroupOld',
        //'SECT_POINT_OF_ENTRY' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetSections',
        'GET_IMAGE_URI' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetImage/',
        'REFERENCE_URL' => 'http://kocmo1c.sellwin.by/Kosmo_Sergey/hs/Kocmo/GetReference/'
    ],
];